CREATE TABLE news_articles (
    id BIGINT NOT NULL AUTO_INCREMENT,
    article_key CHAR(64) NOT NULL,
    category_code VARCHAR(50) NOT NULL,
    category_name VARCHAR(80) NOT NULL,
    query_text VARCHAR(120) NOT NULL,
    title VARCHAR(500) NOT NULL,
    description VARCHAR(1000) NULL,
    origin_link VARCHAR(700) NULL,
    link VARCHAR(700) NOT NULL,
    publisher VARCHAR(100) NULL,
    published_at TIMESTAMP NULL,
    ai_summary VARCHAR(2000) NULL,
    market_sentiment VARCHAR(50) NULL,
    fetched_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_news_articles_key (article_key),
    KEY idx_news_articles_category_published (category_code, published_at),
    KEY idx_news_articles_published_at (published_at)
);
